### ISSUE TITLE
Ports in application.properties

### ISSUE THREAD

**Issue by mum-viadee** [hmolsen/vulnerads#2]
Hi Hannes,

the ports as specified in the file application.properties are not working on linux systems unless you start vulnerads as root or with sudo. Please use the default ports on tomcat (http -> 8080 / https -> 8443).

Greetings,
Martin

**Comment by hmolsen** [comment]
Hi Martin,

thanks for raising the issue. This is actually on purpose, despite having the drawback of the necessity of root/sudo.

First, https during development is very important, as it will bring up issues with mixed content errors, certificate expiration, certificate chain issues, trust store errors, etc. during dev and not only when it's in production. In addition, there are several features that can only be used and tested when the application is served via HTTPS, these are, among others:
- Cookies with the `secure` flag
- HTTP `Strict Transport Security` Header

The latter causes the browsers to redirect automatically from Port 80 to Port 443, other non-standard ports are not automatically redirected, as the browser does not no which ports you have the https connector connected to (cf. https://tools.ietf.org/html/rfc6797#section-8.3).

As my Training-VM is now running Kali Linux and this (until the latest version) was default-root, this was not an issue. In the next VM I am planning to use Kali 2020.1, which runs non-root by default.

Then, instead of sudo'ing the whole process or root'ing the whole user, the best practice is - afaik - to allow the non-root-process to bind to <1024 ports, by explicitely allowing this. With a spring boot app the process binding the port is java:

```
root@kali:~# netstat -lnp
tcp6       0      0 :::443                  :::*                    LISTEN      9557/java
```

```
root@kali:~# readlink -e `which java`
/usr/lib/jvm/java-11-openjdk-amd64/bin/java
```

and then you do

``
sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/lib/jvm/java-11-openjdk-amd64/bin/java
``

cf. https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443

That should allow java to bind to 80/443 withour root privileges.

Best Regards,
Hannes

**Comment by hmolsen** [comment]
Update: I have gone back to the default ports 8080 and 8443, and use iptables to reroute internally. This is the most secure and usable solution I am currently aware of:

== Redirect 80 to 8080, 443 to 8443:
sudo iptables -t nat -A OUTPUT -o lo -p tcp --dport 80 -j REDIRECT --to-port 8080
sudo iptables -t nat -A OUTPUT -o lo -p tcp --dport 443 -j REDIRECT --to-port 8443
sudo apt install iptables-persistent
sudo systemctl enable netfilter-persistent.service

**Comment by mum-viadee** [comment]
Thanks for the info.
